<a href="https://colab.research.google.com/github/MaxMedland/Data-Technician-Bootcamp/blob/main/Python/Pandas_practie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas > /dev/null 2>&1 # > /dev/null 2>&1  <- use to not get import code
import pandas as pd
pd.__version__ # check version

'2.2.2'

In [ ]:
df = pd.read_csv('student.csv')
#df.shape # rows and columns
df.info() # general summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [ ]:
df.head() # .head(n) list top n rows | defalut is 5

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.columns # list column names

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
df.describe() # statistical summary for numberic columns

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [ ]:
# Counts duplicate rows.
df.duplicated().sum()

np.int64(0)

In [ ]:
# subseting data
df[['name','mark']].head()

         name  mark
0    John Deo    75
1    Max Ruin    85
2      Arnold    55
3  Krish Star    60
4   John Mike    60

In [ ]:
# .loc[] uses labels [ rows index, coulmns labes]
# .iloc[] uses index numbers [ rows index, coulmns index]
df.loc[2:10,['id','name','mark']]

    id         name  mark
2    3       Arnold    55
3    4   Krish Star    60
4    5    John Mike    60
5    6    Alex John    55
6    7  My John Rob    78
7    8       Asruid    85
8    9      Tes Qry    78
9   10     Big John    55
10  11       Ronald    89

In [ ]:
# .iloc[] to produce the same as above
#includes all rows upto (not including) the last one mentioned
df.iloc[2:11,[0,1,4]]

    id         name  gender
2    3       Arnold    male
3    4   Krish Star  female
4    5    John Mike  female
5    6    Alex John    male
6    7  My John Rob    male
7    8       Asruid    male
8    9      Tes Qry     NaN
9   10     Big John  female
10  11       Ronald  female

In [ ]:
# filter data using subsetting/slicing
df[df['mark']>60] # also known as boolean masking

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78     NaN
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
26  27          NaN  Three    81     NaN
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
33  34     Gain Toe  Seven    69    male
34  35   Rows Noump    Six    88  female

In [ ]:
df[df['gender']=='female'].head()

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
10  11      Ronald   Six    89  female

In [ ]:
#df[(condition 1) & (condition 2)]
df[(df['gender']=='female') & (df['class']=='Four')]

    id        name class  mark  gender
0    1    John Deo  Four    75  female
3    4  Krish Star  Four    60  female
4    5   John Mike  Four    60  female
9   10    Big John  Four    55  female
20  21  Babby John  Four    69  female

In [ ]:
df[(df['mark']<70) & (df['class']=='Seven')]

    id         name  class  mark  gender
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
33  34     Gain Toe  Seven    69    male

In [ ]:
# df[ (df["mark"]<70) & (df["class"]=="Seven")]
df.loc[(df["mark"]<70) & (df["class"]=="Seven"), :]

    id         name  class  mark  gender
21  22       Reggid  Seven    55  female
28  29  Tess Played  Seven    55    male
33  34     Gain Toe  Seven    69    male

In [ ]:
# Other ways to filer dataframes
# df.filter(items=['name', 'mark']).head()
# df.filter(like='ma').head()
# df.query('mark > 60')

**Practice questions**


Write Python code to calculate



Average mark across all students

Average mark across male and average mark across female students

Max and min mark

Max mark for male and max mark for female students

Average mark for class 'Five'

Average mark for class 'Six' and male students only

In [ ]:
# Average mark across all students
df['mark'].mean()

np.float64(74.65714285714286)

In [ ]:
# Average mark across male and average mark across female students
df.groupby('gender')['mark'].mean()

gender
female    77.312500
male      71.588235
Name: mark, dtype: float64

In [ ]:
# Max and min mark
print(df['mark'].max(),df['mark'].min())

96 18

In [ ]:
# Max mark for male and max mark for female students
df.groupby('gender')['mark'].max()

gender
female    96
male      88
Name: mark, dtype: int64

In [ ]:
# Average mark for class 'Five'
df[df['class']=='Five']['mark'].mean()

np.float64(80.0)

In [ ]:
# Average mark for class 'Six' and male students only
df[(df['class']=='Six') & (df['gender']=='male')]['mark'].mean()

np.float64(54.0)

In [ ]:
df.sort_values(by='id').head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df['mark'].sort_values().head()

18    18
16    54
2     55
5     55
28    55
Name: mark, dtype: int64

In [ ]:
# find male student with their mark higher than 70 and sort by their class
df.loc[(df["gender"]=="male") & (df["mark"]>70)].sort_values(by="class")

    id         name  class  mark gender
22  23        Herod  Eight    79   male
6    7  My John Rob  Fifth    78   male
7    8       Asruid   Five    85   male
17  18        Honny   Five    75   male
15  16        Gimmy   Four    88   male
30  31  Marry Toeey   Four    88   male
23  24    Tiddy Now  Seven    78   male
24  25     Giff Tow  Seven    88   male
25  26       Crelea  Seven    79   male
1    2     Max Ruin  Three    85   male
14  15     Tade Row    NaN    88   male

In [ ]:
# Write code to find information of female students who are above the classroom average. Sort the results in descending order.
df[(df['gender']=='female')&(df['mark']>df['mark'].mean())].sort_values(by='mark',ascending=False)

    id        name  class  mark  gender
32  33   Kenn Rein    Six    96  female
11  12       Recky    Six    94  female
31  32   Binn Rott  Seven    90  female
10  11      Ronald    Six    89  female
34  35  Rows Noump    Six    88  female
12  13         Kty  Seven    88  female
13  14        Bigy  Seven    88  female
27  28   Rojj Base  Seven    86  female
29  30   Reppy Red    Six    79  female
0    1    John Deo   Four    75  female

In [ ]:
df['gender'].value_counts()

gender
male      17
female    16
Name: count, dtype: int64